"""Render supplementary quantum-circuit schematics for the QEC testbed.

The simulation code constructs encoded states analytically, then applies a
Qiskit circuit-level syndrome-recovery channel in ``biqmn.core.encoding``.  This
script exports paper-facing PNGs that show both the encoding convention and the
actual syndrome-extraction/recovery logic.
"""
from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.image as mpimg
import matplotlib.pyplot as plt
from qiskit import ClassicalRegister, QuantumCircuit, QuantumRegister
from qiskit.circuit import Gate


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "figs" / "supplementary_circuits"

STYLE = {
    "name": "iqp",
    "backgroundcolor": "#ffffff",
    "textcolor": "#1f2933",
    "linecolor": "#1f2933",
    "fontsize": 12,
    "subfontsize": 8,
    "displaytext": {
        "h": "H",
        "x": "X",
        "cx": "CX",
        "measure": "M",
        "barrier": "",
    },
}


def _system_registers() -> tuple[QuantumRegister, QuantumRegister, ClassicalRegister]:
    data = QuantumRegister(3, "q")
    anc = QuantumRegister(2, "a")
    syn = ClassicalRegister(2, "s")
    return data, anc, syn


def _draw_png(qc: QuantumCircuit, path: Path, *, scale: float = 0.92) -> None:
    fig = qc.draw(
        output="mpl",
        style=STYLE,
        cregbundle=False,
        idle_wires=True,
        fold=-1,
        scale=scale,
        justify="left",
    )
    fig.savefig(path, dpi=300, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def _append_data_state(qc: QuantumCircuit, data: QuantumRegister) -> None:
    rho_gate = Gate("rho_data(tau)", 3, [])
    qc.append(rho_gate, [data[0], data[1], data[2]])
    qc.barrier()


def _append_bitflip_syndrome(qc: QuantumCircuit, data: QuantumRegister, anc: QuantumRegister, syn: ClassicalRegister) -> None:
    # s[0] records parity q0-q1; s[1] records parity q1-q2.
    qc.cx(data[0], anc[0])
    qc.cx(data[1], anc[0])
    qc.cx(data[1], anc[1])
    qc.cx(data[2], anc[1])
    qc.measure(anc[0], syn[0])
    qc.measure(anc[1], syn[1])
    qc.barrier()


def bitflip_encoding() -> QuantumCircuit:
    q = QuantumRegister(3, "q")
    qc = QuantumCircuit(q, name="bitflip_encoding")
    psi = Gate("psi_L input", 1, [])
    qc.append(psi, [q[0]])
    qc.cx(q[0], q[1])
    qc.cx(q[0], q[2])
    return qc


def phaseflip_encoding() -> QuantumCircuit:
    q = QuantumRegister(3, "q")
    qc = QuantumCircuit(q, name="phaseflip_encoding")
    psi = Gate("psi_L input", 1, [])
    qc.append(psi, [q[0]])
    qc.cx(q[0], q[1])
    qc.cx(q[0], q[2])
    qc.barrier()
    qc.h(q[0])
    qc.h(q[1])
    qc.h(q[2])
    return qc


def bitflip_recovery() -> QuantumCircuit:
    data, anc, syn = _system_registers()
    qc = QuantumCircuit(data, anc, syn, name="bitflip_syndrome_recovery")
    _append_data_state(qc, data)
    _append_bitflip_syndrome(qc, data, anc, syn)

    # Classical integer convention: s[1]s[0], with s[0] as LSB.
    with qc.if_test((syn, 1)):
        qc.x(data[0])
    with qc.if_test((syn, 3)):
        qc.x(data[1])
    with qc.if_test((syn, 2)):
        qc.x(data[2])
    return qc


def phaseflip_recovery() -> QuantumCircuit:
    data, anc, syn = _system_registers()
    qc = QuantumCircuit(data, anc, syn, name="phaseflip_syndrome_recovery")
    _append_data_state(qc, data)
    qc.h(data[0])
    qc.h(data[1])
    qc.h(data[2])
    qc.barrier()
    _append_bitflip_syndrome(qc, data, anc, syn)

    with qc.if_test((syn, 1)):
        qc.x(data[0])
    with qc.if_test((syn, 3)):
        qc.x(data[1])
    with qc.if_test((syn, 2)):
        qc.x(data[2])
    qc.barrier()
    qc.h(data[0])
    qc.h(data[1])
    qc.h(data[2])
    return qc


def make_composite(paths: dict[str, Path], out_path: Path) -> None:
    panels = [
        ("a", "Bit-flip logical encoding", paths["bitflip_encoding"]),
        ("b", "Phase-flip logical encoding", paths["phaseflip_encoding"]),
        ("c", "Bit-flip syndrome extraction and feed-forward recovery", paths["bitflip_recovery"]),
        ("d", "Phase-flip syndrome extraction and feed-forward recovery", paths["phaseflip_recovery"]),
    ]
    fig, axes = plt.subplots(2, 2, figsize=(12.0, 7.0), constrained_layout=True)
    for ax, (label, title, image_path) in zip(axes.ravel(), panels):
        image = mpimg.imread(image_path)
        ax.imshow(image)
        ax.set_axis_off()
        ax.set_title(f"({label}) {title}", loc="left", fontsize=10, pad=4)
    fig.savefig(out_path, dpi=300, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)


def write_manifest(paths: dict[str, Path]) -> None:
    lines = [
        "# Supplementary QEC circuit assets",
        "",
        "Generated by `manuscript/scripts/make_supplementary_circuits.py`.",
        "",
        "These schematics use system-qubit order `q_0, q_1, q_2` for readability.",
        "The implementation in `biqmn.core.encoding` reverses the Qiskit data register internally to preserve numpy kron ordering.",
        "",
        "| File | Use |",
        "| --- | --- |",
    ]
    rows = {
        "supp_qec_circuit_panel.png": "Composite 2x2 panel for Supplementary Information.",
        "supp_bitflip_encoding.png": "Three-qubit bit-flip repetition-code encoding convention.",
        "supp_phaseflip_encoding.png": "Three-qubit phase-flip repetition-code encoding convention.",
        "supp_bitflip_syndrome_recovery.png": "Circuit-level bit-flip syndrome extraction and feed-forward correction.",
        "supp_phaseflip_syndrome_recovery.png": "Circuit-level phase-flip syndrome extraction and feed-forward correction.",
    }
    for name, desc in rows.items():
        lines.append(f"| `{name}` | {desc} |")
    lines.extend(
        [
            "",
            "Suggested LaTeX include:",
            "",
            "```tex",
            "\\begin{figure}[t]",
            "\\centering",
            "\\includegraphics[width=\\textwidth]{figs/supplementary_circuits/supp_qec_circuit_panel.png}",
            "\\caption{Circuit schematics for the encoded-QEC testbed. Panels show the logical encoding conventions and the syndrome-extraction/feed-forward recovery circuits used for the three-qubit bit-flip and phase-flip repetition codes.}",
            "\\label{fig:supp-qec-circuits}",
            "\\end{figure}",
            "```",
            "",
        ]
    )
    (OUT_DIR / "README.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    circuits = {
        "bitflip_encoding": bitflip_encoding(),
        "phaseflip_encoding": phaseflip_encoding(),
        "bitflip_recovery": bitflip_recovery(),
        "phaseflip_recovery": phaseflip_recovery(),
    }
    paths = {
        "bitflip_encoding": OUT_DIR / "supp_bitflip_encoding.png",
        "phaseflip_encoding": OUT_DIR / "supp_phaseflip_encoding.png",
        "bitflip_recovery": OUT_DIR / "supp_bitflip_syndrome_recovery.png",
        "phaseflip_recovery": OUT_DIR / "supp_phaseflip_syndrome_recovery.png",
    }
    for key, circuit in circuits.items():
        _draw_png(circuit, paths[key], scale=0.88 if "recovery" in key else 0.95)

    paths["panel"] = OUT_DIR / "supp_qec_circuit_panel.png"
    make_composite(paths, paths["panel"])
    write_manifest(paths)


if __name__ == "__main__":
    main()
